### ISSUE TITLE
Point out that "Additional information about Kiwi TCMS subscriptions" is clickable

### ISSUE THREAD

**Issue by RMadjev** [kiwitcms/kiwitcms.github.io#119]
![Screenshot_20200802_001002](https://user-images.githubusercontent.com/8727922/89110685-ea833f00-d455-11ea-896d-a9aeb562e6aa.png)
![Screenshot_20200802_000859](https://user-images.githubusercontent.com/8727922/89110687-eb1bd580-d455-11ea-9407-5f3542d8aad4.png)

**Comment by RMadjev** [comment]
On hover the cursor is different as pointed out in the screenshots.

**Comment by atodorov** [comment]
Fixed in https://github.com/kiwitcms/kiwitcms.github.io/commit/7e49c0b09ceabc1cab609a8e5c96d211b2afaa1b
