### ISSUE TITLE
Add social sharing buttons

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/kiwitcms.github.io#27]
We need social sharing buttons both for users to be able to share but also for us to be able to track sharing and receive insight into what's going on with the project.

The following JS needs to go at the bottom of the page, before the closing body tag:
```
<!-- Go to www.addthis.com/dashboard to customize your tools --> <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50fb0d604eb24fd0"></script> 
```

This snippet is the containers where the buttons will be rendered:
```
<!-- Go to www.addthis.com/dashboard to customize your tools --> <div class="addthis_inline_share_toolbox"></div>
```

NOTES:

* Make the pubid a setting with the name ADDTHIS_PUBID, similar to other existing settings
* You should be able to test this locally since it doesn't require additional CSS
* These buttons should be visible only for individual blog posts
* I'm thinking about placing them right above the comments section. Please implement it this way and we'll see how it looks.

**Comment by ivo0126** [comment]
Between which sections is the "comments" section? I don't see it anywhere locally, while in production mode, or on the official website.
