### ISSUE TITLE
The icons are not aligned

### ISSUE THREAD

**Issue by renystankova** [kiwitcms/kiwitcms.github.io#35]
The icons are not well aligned using chrome - see attached screen
The icons are liquid when resize the browser's window - this causes also unsettlement of these icons.
http://kiwitcms.org/
![image](https://user-images.githubusercontent.com/44020270/50458799-96a59f80-096e-11e9-81dd-1c2e1b9f20c4.png)
![image](https://user-images.githubusercontent.com/44020270/50458833-cce31f00-096e-11e9-87e7-604432fa1ca4.png)

**Comment by atodorov** [comment]
Confirmed with screen size 1024px (width).

@ivo0126 can you figure out what is going on here.
