### ISSUE TITLE
Feature matrix & HW requirements

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/kiwitcms.github.io#71]
We need to bring back the feature matrix as a table comparing Kiwi TCMS against other known applications b/c people are asking for it.

Also while at it document at least the basic HW requirements (which are none, we use unoptimized AWS t2.small instance and just run containers on it):
https://aws.amazon.com/ec2/instance-types/

**Comment by atodorov** [comment]
Feature matrix is here https://kiwitcms.org/features/

we're still missing hardware requirements

**Comment by albertlinga** [comment]
I'm evaluating this tool and would've loved to see a documentation on the hardware requirements since admins will require those.

**Comment by atodorov** [comment]
@albertlinga thanks for evaluating Kiwi TCMS. 

We're still missing h/w requirements but the results recorded at https://kiwitcms.org/blog/atodorov/2018/10/26/kiwi-tcms-api-performance-baseline/ are measured on a t2.micro AWS instance so there isn't much in terms of requirements anyway.

The deployment uses a bigger EC2 instance b/c we need more RAM for running multiple containers. Disk I/O, CPU and network haven't changed in any significant way. 

Kiwi TCMS is predominantly I/O bound application so you need fast disk and maybe network if the DB is separate. Email me if you need more info.

**Comment by atodorov** [comment]
Hardware & performance results recorded at https://kiwitcms.readthedocs.io/en/latest/hardware_performance.html.
